# Generated by Django 6.0.1 on 2026-08-17 12:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='area',
            field=models.CharField(blank=True, default='', help_text='Cuisine / country origin, e.g. Italian, Mexican.', max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, default=None, help_text='External recipe ID (e.g. TheMealDB meal id) to prevent duplicate stashes.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='Direct image URL if available.', max_length=1000),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(blank=True, default='', help_text='Step-by-step preparation instructions.'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='source_type',
            field=models.CharField(default='custom', help_text="'custom' for user-created recipes, 'themealdb' for recipes stashed from TheMealDB.", max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(blank=True, default='Dinner', max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Optional cooking notes or tips.'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='source_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('owner', 'external_id'), name='unique_owner_external_id'),
        ),
    ]
